services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  VV\T3meilisearch\:
    resource: '../Classes/*'

  VV\T3meilisearch\EventListener\IndexContent:
    tags:
      - name: event.listener

  VV\T3meilisearch\EventListener\AddVersionToSystemInformationToolbar:
   tags:
      - name: event.listener
