name: Tests

on: push

jobs:
  codingstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up PHP Version
        run: sudo update-alternatives --set php /usr/bin/php8.0

      - name: Install requirements
        run: composer global require --dev friendsofphp/php-cs-fixer

      - name: Check dir
        run: ls -al /home/runner/.composer/

      - name: Execute style check
        run: /home/runner/.composer/vendor/bin/php-cs-fixer fix --dry-run --diff
