name: Tests

on: push

jobs:
  codingstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install requirements
        run: composer global require --dev friendsofphp/php-cs-fixer

      - name: Execute style check
        run: /home/runner/.composer/vendor/bin/php-cs-fixer fix --dry-run --diff
